# Generated by Django 3.1.3 on 2020-11-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsayapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowsay',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
